spring:
  profiles:
    active: DEV
  datasource:
    url: jdbc:mariadb://www.pantry.ovh:3306/TravelExpress
    username: back
    password: fast
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
